import { test, expect, type APIRequestContext } from '@playwright/test'
import { readFile, writeFile, mkdir, unlink, access } from 'node:fs/promises'
import path from 'node:path'
import type { DocumentContent, Project } from '../src/models'

// The test workspace is seeded with the demo project on first start; every project is one folder inside it.
const workspaceRoot = path.resolve('../.test-data/browser')
const projectSlug = 'Sample manuscript'
const projectUrl = `/p/${encodeURIComponent(projectSlug)}`
const apiBase = `/api/projects/${encodeURIComponent(projectSlug)}`
const fixtureRoot = path.join(workspaceRoot, projectSlug)
const title = (prefix: string) => `${prefix} ${Date.now()}`
async function create(request: APIRequestContext, name: string, content: string) {
  const response = await request.post(`${apiBase}/documents`, { data: { title: name, folder: 'Manuscript/Browser checks', content } })
  expect(response.ok()).toBeTruthy()
  return (await response.json()).data as DocumentContent
}
// API responses are enveloped as { apiVersion, data }.
async function getProject(request: APIRequestContext) {
  return (await (await request.get(apiBase)).json()).data as Project
}

test('writing workspace renders without browser errors and switches views', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(projectUrl)
  await expect(page.getByRole('heading', { name: 'The letter arrives', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Manuscript editor' })).toContainText('The letter arrived on a Tuesday')
  await page.screenshot({ path: '../.test-data/odysseum-writing.png', fullPage: true })
  await page.getByRole('tab', { name: 'Corkboard' }).click()
  await expect(page.getByRole('heading', { name: 'A story taking shape' })).toBeVisible()
  expect(await page.locator('.scene-card').count()).toBeGreaterThanOrEqual(5)
  await expect(page.locator('.scene-card .status-pill').first()).toContainText('First draft')
  await page.screenshot({ path: '../.test-data/odysseum-corkboard.png', fullPage: true })
  await page.getByRole('tab', { name: 'Outline' }).click()
  expect(await page.locator('.outline-table tbody tr').count()).toBeGreaterThanOrEqual(5)
  await page.getByRole('tab', { name: 'Write', exact: true }).click()
  await page.getByRole('button', { name: 'Read', exact: true }).click()
  await expect(page.locator('.rendered-markdown strong')).toContainText('The island is not where we left it.')
  expect(errors).toEqual([])
})

test('creates and edits a real Markdown file and persists scene details', async ({ page }) => {
  const name = title('A new beginning')
  await page.goto(projectUrl)
  await page.getByRole('button', { name: 'Add scene', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).last().fill(name)
  await page.getByRole('button', { name: 'Create scene', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await editor.fill('The rain stopped.\n\nA **new** chapter began.')
  await expect(page.getByRole('button', { name: 'All changes saved', exact: true })).toBeVisible()
  const doc = (await getProject(page.request)).documents.find(item => item.title === name)!
  const raw = await readFile(path.join(fixtureRoot, doc.path), 'utf8')
  expect(raw).toContain('writer_id:')
  expect(raw).toContain('A **new** chapter began.')
  await page.getByRole('textbox', { name: 'Synopsis', exact: false }).fill('The beginning of something unexpected.')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save details', exact: true })).toBeHidden()
  await page.reload()
  await expect(editor).toContainText('A new chapter began.')
  await expect(page.getByRole('textbox', { name: 'Synopsis', exact: false })).toHaveValue('The beginning of something unexpected.')
})

test('discovers an external file and reloads a clean editor after external saves', async ({ page }) => {
  const name = title('External scene')
  const folder = path.join(fixtureRoot, 'Manuscript', 'External checks')
  await mkdir(folder, { recursive: true })
  const file = path.join(folder, `${name}.md`)
  await page.goto(projectUrl)
  await writeFile(file, 'Written in another editor.\n')
  await page.getByRole('button', { name, exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(editor).toContainText('Written in another editor.')
  await writeFile(file, 'Changed directly on the filesystem.\n')
  await expect(editor).toContainText('Changed directly on the filesystem.')
})

test('keeps a browser draft when an external edit conflicts', async ({ page, request }) => {
  const name = title('Conflicting scene')
  const doc = await create(request, name, 'Original paragraph.')
  await page.goto(projectUrl)
  await page.getByRole('button', { name, exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(editor).toContainText('Original paragraph.')
  const file = path.join(fixtureRoot, doc.document.path)
  const raw = await readFile(file, 'utf8')
  // Delay saves so the independent filesystem edit is guaranteed to win this race.
  await page.route(`**${apiBase}/documents/${doc.document.id}`, async route => {
    if (route.request().method() === 'PUT') await new Promise(resolve => setTimeout(resolve, 500))
    await route.continue()
  })
  await editor.fill('My browser draft must survive.')
  await writeFile(file, raw.replace('Original paragraph.', 'The version from my other editor.'))
  // The footer save indicator also reads "Review changes" during a conflict, so scope to the notice bar.
  const review = page.locator('.notice-bar').getByRole('button', { name: 'Review changes', exact: true })
  await expect(review).toBeVisible()
  await expect(editor).toContainText('My browser draft must survive.')
  expect(await readFile(file, 'utf8')).toContain('The version from my other editor.')
  await review.click()
  await expect(page.getByRole('textbox', { name: 'Your browser draft' })).toHaveValue('My browser draft must survive.')
  await expect(page.locator('.conflict-columns pre')).toContainText('The version from my other editor.')
  await page.getByRole('button', { name: 'Save my version', exact: true }).click()
  await expect(page.getByRole('button', { name: 'All changes saved', exact: true })).toBeVisible()
  expect(await readFile(file, 'utf8')).toContain('My browser draft must survive.')
})

test('keeps an edit made while saves fail and syncs it once they succeed', async ({ page, request }) => {
  const name = title('Recovered scene')
  const doc = await create(request, name, 'Saved beginning.')
  await page.goto(projectUrl)
  await page.getByRole('button', { name, exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(editor).toContainText('Saved beginning.')
  await page.route(`**${apiBase}/documents/${doc.document.id}`, route => route.request().method() === 'PUT' ? route.abort() : route.continue())
  await editor.fill('An unsaved thought worth keeping.')
  await expect(page.getByRole('button', { name: 'Saved on this device', exact: true })).toBeVisible()
  await expect(page.getByText(/1 change waiting/)).toBeVisible()
  await page.reload()
  await expect(editor).toContainText('An unsaved thought worth keeping.')
  await page.unroute(`**${apiBase}/documents/${doc.document.id}`)
  // No button, no keystroke: the engine retries on its own.
  await expect(page.getByRole('button', { name: 'All changes saved', exact: true })).toBeVisible({ timeout: 15000 })
  expect(await readFile(path.join(fixtureRoot, doc.document.path), 'utf8')).toContain('An unsaved thought worth keeping.')
})

test('keeps working offline: reloads from the local copy, accepts edits, and syncs when back', async ({ page, context, request }) => {
  const name = title('Offline scene')
  const doc = await create(request, name, 'Written while online.')
  await page.goto(projectUrl)
  await page.getByRole('button', { name, exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(editor).toContainText('Written while online.')
  await expect(page.getByText('Connected to your files')).toBeVisible()
  await page.evaluate(() => navigator.serviceWorker.ready)
  await context.setOffline(true)
  await page.reload()
  await expect(editor).toContainText('Written while online.')
  await expect(page.locator('.binder-footer')).toContainText('Offline')
  await editor.fill('Written on the train, far from any server.')
  await expect(page.getByRole('button', { name: 'Saved on this device', exact: true })).toBeVisible()
  await page.reload()
  await expect(editor).toContainText('Written on the train, far from any server.')
  await page.getByRole('tab', { name: 'Corkboard' }).click()
  await expect(page.locator('.scene-card').count()).resolves.toBeGreaterThanOrEqual(5)
  await page.getByRole('tab', { name: 'Write', exact: true }).click()
  // Everything else works offline too: a new scene, its details, project settings, search.
  const born = `Born offline ${Date.now()}`
  await page.getByRole('button', { name: 'Add scene', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).last().fill(born)
  await page.getByRole('button', { name: 'Create scene', exact: true }).click()
  await expect(page.getByRole('heading', { name: born, exact: true })).toBeVisible()
  await editor.fill('A scene that began without a server.')
  await page.getByRole('textbox', { name: 'Synopsis', exact: false }).fill('Conceived in airplane mode.')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save details', exact: true })).toBeHidden()
  await page.getByRole('button', { name: /Find anything/ }).click()
  await page.getByRole('textbox', { name: 'Search manuscript' }).fill(born)
  await expect(page.locator('.search-results strong').first()).toHaveText(born)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Edit manuscript goal', exact: true }).click()
  await page.getByLabel('Manuscript word goal').fill('80000')
  await page.getByRole('button', { name: 'Save workspace', exact: true }).click()
  await expect(page.locator('.project-progress > strong')).toContainText('80,000')
  await page.reload()
  await expect(page.getByRole('button', { name: born, exact: true })).toBeVisible()
  await expect(page.locator('.project-progress > strong')).toContainText('80,000')
  await context.setOffline(false)
  await expect(page.getByText('Connected to your files')).toBeVisible({ timeout: 20000 })
  await expect.poll(async () => {
    const project = (await (await request.get(apiBase)).json()).data
    const scene = project.documents.find((item: { title: string }) => item.title === born)
    return scene ? { synopsis: scene.synopsis, goal: project.settings.wordGoal } : null
  }, { timeout: 20000 }).toEqual({ synopsis: 'Conceived in airplane mode.', goal: 80000 })
  const synced = (await (await request.get(apiBase)).json()).data
  const scene = synced.documents.find((item: { title: string }) => item.title === born)
  await expect.poll(() => readFile(path.join(fixtureRoot, scene.path), 'utf8').catch(() => ''), { timeout: 15000 }).toContain('A scene that began without a server.')
  await expect.poll(() => readFile(path.join(fixtureRoot, doc.document.path), 'utf8'), { timeout: 15000 }).toContain('Written on the train, far from any server.')
})

test('external deletion does not silently recreate a document', async ({ page, request }) => {
  const name = title('Removed scene')
  const doc = await create(request, name, 'Remember this text.')
  await page.goto(projectUrl)
  await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Manuscript editor' })).toContainText('Remember this text.')
  const file = path.join(fixtureRoot, doc.document.path)
  await unlink(file)
  await expect(page.getByText('This file was removed. Your text is still here.')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Manuscript editor' })).toContainText('Remember this text.')
  await expect(readFile(file)).rejects.toThrow()
})

test('history, search, move, settings, and reorder all address the open project', async ({ page, request }) => {
  const name = title('Toolbox scene')
  await create(request, name, 'A lantern swung in the dark.')
  await page.goto(projectUrl)
  await page.getByRole('button', { name, exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Manuscript editor' })
  await expect(editor).toContainText('A lantern swung in the dark.')
  await editor.fill('A lantern swung in the dark. Then it went out.')
  await expect(page.getByRole('button', { name: 'All changes saved', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Version history/ }).click()
  await page.locator('.snapshot-list button').first().click()
  await expect(page.locator('.snapshot-preview')).toContainText('A lantern swung in the dark.')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: /Find anything/ }).click()
  // Search by the unique title: earlier runs leave similar prose behind in the shared test workspace.
  await page.getByRole('textbox', { name: 'Search manuscript' }).fill(name)
  await expect(page.locator('.search-results strong').first()).toHaveText(name)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Move or rename file/ }).click()
  const movedPath = `Manuscript/Moved checks/${name}.md`
  await page.getByLabel('Path within your workspace').fill(movedPath)
  await page.getByRole('button', { name: 'Move file', exact: true }).click()
  await expect(page.locator('.file-location code')).toHaveText(movedPath)
  await expect.poll(() => access(path.join(fixtureRoot, movedPath)).then(() => true, () => false)).toBe(true)
  await page.getByRole('button', { name: 'Edit manuscript goal', exact: true }).click()
  await page.getByLabel('Manuscript word goal').fill('75000')
  await page.getByRole('button', { name: 'Save workspace', exact: true }).click()
  await expect(page.locator('.project-progress > strong')).toContainText('75,000')
  await page.getByRole('tab', { name: 'Outline' }).click()
  const before = (await getProject(page.request)).documents.map(doc => doc.id)
  await page.locator('.outline-table tbody tr').last().getByRole('button', { name: 'Move scene earlier' }).click()
  await expect.poll(async () => (await getProject(page.request)).documents.map(doc => doc.id)).not.toEqual(before)
})

test('creates a second project as its own folder and switches between projects', async ({ page }) => {
  const name = title('Second book')
  await page.goto(projectUrl)
  await page.getByRole('button', { name: 'Switch project', exact: true }).click()
  await page.getByRole('textbox', { name: 'New project', exact: true }).fill(name)
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(page).toHaveURL(`/p/${encodeURIComponent(name)}`)
  await expect(page.getByRole('heading', { name: 'A blank page. Endless possibility.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Switch project', exact: true })).toContainText(name)
  await expect.poll(() => access(path.join(workspaceRoot, name, '.writer', 'project.json')).then(() => true, () => false)).toBe(true)
  await expect(page).toHaveTitle(`${name} — Odysseum`)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Switch project', exact: true })).toContainText(name)
  await page.getByRole('button', { name: 'Switch project', exact: true }).click()
  await page.locator('.project-list').getByRole('button', { name: 'The Cartographer’s Daughter' }).click()
  await expect(page).toHaveURL(projectUrl)
  await expect(page.getByRole('textbox', { name: 'Manuscript editor' })).toContainText('The letter arrived on a Tuesday')
  await page.getByRole('button', { name: 'Switch project', exact: true }).click()
  await page.getByRole('button', { name: 'All projects', exact: true }).click()
  await expect(page).toHaveURL('/')
  await expect(page.getByRole('heading', { name: 'Which story today?' })).toBeVisible()
  await expect(page.locator('.project-list').getByRole('button', { name })).toBeVisible()
})

test('characters are documents of their own and attach to scenes', async ({ page, request }) => {
  const hero = title('Character')
  await page.goto(projectUrl)
  await page.getByRole('button', { name: /^Characters/ }).click()
  await page.getByRole('button', { name: 'Add character', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).last().fill(hero)
  await expect(page.getByLabel('Folder')).toHaveValue('Characters')
  await page.getByRole('button', { name: 'Create character', exact: true }).click()
  await expect(page.getByRole('heading', { name: hero, exact: true })).toBeVisible()
  await expect(page.getByText('APPEARS IN')).toBeVisible()
  await expect(page.getByText('Not in any scene yet.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: /^Manuscript/ }).click()
  await page.getByRole('button', { name: 'The letter arrives', exact: true }).click()
  const chip = page.locator('.character-picker').getByRole('button', { name: hero, exact: true })
  await chip.click()
  await expect(chip).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save details', exact: true })).toBeHidden()
  await expect.poll(async () => {
    const docs = (await getProject(request)).documents
    const heroId = docs.find(doc => doc.title === hero)?.id
    return !!heroId && (docs.find(doc => doc.title === 'The letter arrives')?.characters ?? []).includes(heroId)
  }).toBe(true)
  await page.reload()
  await expect(page.locator('.character-picker').getByRole('button', { name: hero, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /^Characters/ }).click()
  await page.locator('.binder-tree').getByRole('button', { name: hero, exact: true }).click()
  await expect(page.locator('.appearances')).toContainText('The letter arrives')
  await page.locator('.appearances').getByRole('button', { name: 'The letter arrives' }).click()
  await expect(page.getByRole('heading', { name: 'The letter arrives', exact: true })).toBeVisible()
})

test('locations created offline keep their scene links when synced', async ({ page, context, request }) => {
  const hero = title('Location')
  await page.goto(projectUrl)
  await expect(page.getByText('Connected to your files')).toBeVisible()
  await page.evaluate(() => navigator.serviceWorker.ready)
  await context.setOffline(true)
  await page.getByRole('button', { name: /^Locations/ }).click()
  await page.getByRole('button', { name: 'Add location', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).last().fill(hero)
  await expect(page.getByLabel('Folder')).toHaveValue('Locations')
  await page.getByRole('button', { name: 'Create location', exact: true }).click()
  await expect(page.getByRole('heading', { name: hero, exact: true })).toBeVisible()
  await expect(page.getByText('APPEARS IN')).toBeVisible()
  await expect(page.getByText('Not in any scene yet.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: /^Manuscript/ }).click()
  await page.getByRole('button', { name: 'The letter arrives', exact: true }).click()
  const chip = page.locator('.location-picker').getByRole('button', { name: hero, exact: true })
  await chip.click()
  await expect(chip).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save details', exact: true })).toBeHidden()
  await page.reload()
  await expect(page.locator('.location-picker').getByRole('button', { name: hero, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await context.setOffline(false)
  await expect.poll(async () => {
    const docs = (await getProject(request)).documents
    const heroId = docs.find(doc => doc.title === hero)?.id
    return !!heroId && (docs.find(doc => doc.title === 'The letter arrives')?.locations ?? []).includes(heroId)
  }, { timeout: 20000 }).toBe(true)
  await page.reload()
  await expect(page.locator('.location-picker').getByRole('button', { name: hero, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /^Locations/ }).click()
  await page.locator('.binder-tree').getByRole('button', { name: hero, exact: true }).click()
  await expect(page.locator('.appearances')).toContainText('The letter arrives')
  await page.locator('.appearances').getByRole('button', { name: 'The letter arrives' }).click()
  await expect(page.getByRole('heading', { name: 'The letter arrives', exact: true })).toBeVisible()
})

test('beats keep independent arc positions through offline creation, dragging, and reload', async ({ page, context, request }) => {
  const race = title('Race')
  const beat = title('Broken promise')
  const wealth = title('Wealth')
  await page.goto(projectUrl)
  await expect(page.getByText('Connected to your files')).toBeVisible()
  await page.evaluate(() => navigator.serviceWorker.ready)
  const before = (await getProject(request)).documents.map(doc => doc.id)
  await context.setOffline(true)
  await page.getByRole('tab', { name: 'Arcs', exact: true }).click()
  for (const name of [race, wealth]) {
    await page.locator('.arcs-view').getByRole('button', { name: 'New arc', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Title', { exact: true }).fill(name)
    await expect(page.getByLabel('Folder', { exact: true })).toHaveValue('Arcs')
    await page.getByRole('button', { name: 'Create arc', exact: true }).click()
    await expect(page.getByRole('region', { name: `${name} arc`, exact: true })).toBeVisible()
  }
  for (const [name, position] of [[race, 3], [wealth, 2]] as const) {
    await page.getByRole('button', { name: `Add beat to ${name}`, exact: true }).click()
    if (name === race) {
      await page.getByLabel('Beat title', { exact: true }).fill(beat)
    } else {
      await page.getByRole('button', { name: 'Existing beat', exact: true }).click()
      const options = page.getByLabel('Beat', { exact: true }).locator('option')
      await expect(options).not.toContainText(['The letter arrives'])
      const option = options.filter({ hasText: beat })
      await page.getByLabel('Beat', { exact: true }).selectOption((await option.getAttribute('value'))!)
    }
    await page.getByLabel('Position', { exact: true }).fill(String(position))
    await page.getByRole('button', { name: name === race ? 'Create beat' : 'Add to arc', exact: true }).click()
  }
  const raceLane = page.getByRole('region', { name: `${race} arc`, exact: true })
  const wealthLane = page.getByRole('region', { name: `${wealth} arc`, exact: true })
  await expect(raceLane.locator('.arc-point')).toHaveAttribute('data-position', '2')
  await expect(wealthLane.locator('.arc-point')).toHaveAttribute('data-position', '1')
  await raceLane.getByRole('button', { name: `Move ${beat} right on ${race}`, exact: true }).click()
  await expect(raceLane.locator('.arc-point')).toHaveAttribute('data-position', '3')
  await expect(wealthLane.locator('.arc-point')).toHaveAttribute('data-position', '1')
  await raceLane.locator('.arc-point').dragTo(raceLane.locator('.arc-track'), { targetPosition: { x: 210, y: 45 } })
  await expect(raceLane.locator('.arc-point')).toHaveAttribute('data-position', '1')
  await page.reload()
  await page.getByRole('tab', { name: 'Arcs', exact: true }).click()
  await expect(raceLane.locator('.arc-point')).toHaveAttribute('data-position', '1')
  await expect(wealthLane.locator('.arc-point')).toHaveAttribute('data-position', '1')
  await context.setOffline(false)
  await expect.poll(async () => {
    const project = (await (await request.get(apiBase)).json()).data
    const a = project.documents.find((doc: { title: string }) => doc.title === race)
    const b = project.documents.find((doc: { title: string }) => doc.title === wealth)
    const scene = project.documents.find((doc: { title: string }) => doc.title === beat)
    return !!a && !!b && !!scene && scene.arcPositions[a.id] === 1 && scene.arcPositions[b.id] === 1
  }, { timeout: 20000 }).toBe(true)
  expect((await getProject(request)).documents.filter(doc => before.includes(doc.id)).map(doc => doc.id)).toEqual(before)
  await page.screenshot({ path: '../.test-data/odysseum-arcs.png', fullPage: true })
  await raceLane.getByRole('button', { name: `Open ${beat}`, exact: true }).click()
  await expect(page.getByRole('heading', { name: beat, exact: true })).toBeVisible()
  await expect(page.getByText('BEAT DETAILS', { exact: true })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Arcs for this beat', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Manuscript editor' }).fill('The promise is broken, and trust begins to unravel.')
  await expect(page.getByRole('button', { name: 'All changes saved', exact: true })).toBeVisible()
  const savedBeat = (await getProject(request)).documents.find(doc => doc.title === beat)!
  expect(savedBeat.kind).toBe('beat')
  expect(savedBeat.path).toMatch(/^Beats\//)
  expect(await readFile(path.join(fixtureRoot, savedBeat.path), 'utf8')).toContain('trust begins to unravel')
  await page.getByRole('tab', { name: 'Arcs', exact: true }).click()
  await raceLane.getByRole('button', { name: `Remove ${beat} from ${race}`, exact: true }).click()
  await expect(raceLane.locator('.arc-point')).toHaveCount(0)
  await expect(wealthLane.locator('.arc-point')).toHaveCount(1)
  await expect.poll(async () => {
    const project = (await (await request.get(apiBase)).json()).data
    const a = project.documents.find((doc: { title: string }) => doc.title === race)
    const b = project.documents.find((doc: { title: string }) => doc.title === wealth)
    const scene = project.documents.find((doc: { title: string }) => doc.title === beat)
    return scene.arcPositions[a.id] === undefined && scene.arcPositions[b.id] === 1
  }).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await page.getByRole('tab', { name: 'Arcs', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Story arcs', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: '../.test-data/odysseum-arcs-mobile.png', fullPage: true })
})

test('mobile layout keeps the writing surface reachable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(projectUrl)
  await expect(page.getByRole('textbox', { name: 'Manuscript editor' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show binder', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: '../.test-data/odysseum-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Show binder', exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'Project binder' })).toBeVisible()
})
